v3.0 Added support for Backup OS & Set Time. Documentation. Splash screen tidy up. Iconcache. Update it, zh_TW translations

diff --git a/buildroot/package/dropbear/S50dropbear b/buildroot/package/dropbear/S50dropbear
--- a/buildroot/package/dropbear/S50dropbear
+++ b/buildroot/package/dropbear/S50dropbear
@@ -9,16 +9,14 @@ test -r /etc/default/dropbear && . /etc/default/dropbear
 start() {
 	DROPBEAR_ARGS="$DROPBEAR_ARGS -R"
 
-	echo -n "Starting dropbear sshd: "
 	umask 077
 	start-stop-daemon -S -q -p /var/run/dropbear.pid \
 		--exec /usr/sbin/dropbear -- $DROPBEAR_ARGS
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && echo "" || echo "Starting dropbear sshd: FAIL"
 }
 stop() {
-	echo -n "Stopping dropbear sshd: "
 	start-stop-daemon -K -q -p /var/run/dropbear.pid
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	[ $? = 0 ] && echo "" || echo "Stopping dropbear sshd: FAIL"
 }
 restart() {
 	stop
